import { Product, Category, Review, Order, Coupon } from "@/types";

export const categories: Category[] = [
  { id: "1", name: "Office Chairs", slug: "office-chairs", icon: "💼", productCount: 24, image: "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=400", status: 1},
  { id: "2", name: "Dining Chairs", slug: "dining-chairs", icon: "🍽️", productCount: 18, image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400", status: 1 },
  { id: "3", name: "Gaming Chairs", slug: "gaming-chairs", icon: "🎮", productCount: 12, image: "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=400", status: 1 },
  { id: "4", name: "Recliner Chairs", slug: "recliner-chairs", icon: "🛋️", productCount: 8, image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400", status: 1 },
  { id: "5", name: "Lounge Chairs", slug: "lounge-chairs", icon: "☕", productCount: 10, image: "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=400", status: 1 },
  { id: "6", name: "Outdoor Chairs", slug: "outdoor-chairs", icon: "🌿", productCount: 14, image: "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=400", status: 1 },
  { id: "7", name: "Foldable Chairs", slug: "foldable-chairs", icon: "📦", productCount: 9, image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400", status: 1 },
  { id: "8", name: "Bar Stools", slug: "bar-stools", icon: "🍸", productCount: 6, image: "https://images.unsplash.com/photo-1561677843-39dee7a319ca?w=400", status: 1 },
  { id: "9", name: "Kids Chairs", slug: "kids-chairs", icon: "🧒", productCount: 7, image: "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=400", status: 1 },
  { id: "10", name: "Armchairs", slug: "armchairs", icon: "🏠", productCount: 11, image: "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=400", status: 1 },
];

export const products: Product[] = [
  {
    id: "p1",
    name: "ErgoMax Pro Mesh Chair",
    brand: "Green Soul",
    category: "office-chairs",
    description: "Premium ergonomic mesh office chair with lumbar support and adjustable armrests. Perfect for long work sessions. Features breathable mesh back that keeps you cool and comfortable throughout the day.",
    material: "High Back Mesh",
    frameMaterial: "Steel",
    seatHeight: "45cm - 55cm",
    weightCapacity: "120 kg",
    armrest: "Adjustable",
    headrest: "Yes",
    recline: "Yes (90-135 degrees)",
    warranty: "2 Years",
    assemblyRequired: true,
    colors: ["Black", "Grey", "Blue"],
    dimensions: "65cm x 65cm x 120cm",
    weight: "12 kg",
    mrp: 18999,
    sellingPrice: 12999,
    gstPercent: 18,
    stockQty: 45,
    sku: "GS-EM-PRO-001",
    images: [
      "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
      "https://images.unsplash.com/photo-1523297467724-f6758d7124c5?w=600",
      "https://images.unsplash.com/photo-1598300042247-d088f8ab3a91?w=600",
    ],
    isFeatured: true,
    rating: 4.5,
    reviewCount: 234,
    tags: ["ergonomic", "mesh", "office", "adjustable"],
  },
  {
    id: "p2",
    name: "Executive Leather Chair",
    brand: "Godrej Interio",
    category: "office-chairs",
    description: "Premium executive leatherette chair with high back support and padded armrests. Adds elegance to your workspace with its refined design and superior comfort.",
    material: "Leatherette",
    frameMaterial: "Aluminum",
    seatHeight: "48cm - 58cm",
    weightCapacity: "100 kg",
    armrest: "Fixed",
    headrest: "Yes",
    recline: "Yes (90-120 degrees)",
    warranty: "1 Year",
    assemblyRequired: true,
    colors: ["Black", "Brown"],
    dimensions: "70cm x 70cm x 125cm",
    weight: "15 kg",
    mrp: 25999,
    sellingPrice: 18999,
    gstPercent: 18,
    stockQty: 20,
    sku: "GI-EX-LEA-002",
    images: [
      "https://images.unsplash.com/photo-1523297467724-f6758d7124c5?w=600",
      "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
    ],
    isFeatured: true,
    rating: 4.3,
    reviewCount: 156,
    tags: ["executive", "leather", "premium", "office"],
  },
  {
    id: "p3",
    name: "Feather Lite Dining Set Chair",
    brand: "Featherlite",
    category: "dining-chairs",
    description: "Elegant dining chair with solid wood frame and fabric upholstery. Perfect for your dining room with its classic design that complements any interior.",
    material: "Fabric",
    frameMaterial: "Solid Wood",
    seatHeight: "45cm",
    weightCapacity: "100 kg",
    armrest: "No",
    headrest: "No",
    recline: "No",
    warranty: "1 Year",
    assemblyRequired: false,
    colors: ["Beige", "Grey", "Blue"],
    dimensions: "55cm x 50cm x 90cm",
    weight: "6 kg",
    mrp: 8999,
    sellingPrice: 5999,
    gstPercent: 12,
    stockQty: 60,
    sku: "FL-DIN-001",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
      "https://images.unsplash.com/photo-1517705008128-361805174694?w=600",
    ],
    isFeatured: false,
    rating: 4.1,
    reviewCount: 89,
    tags: ["dining", "wood", "fabric", "classic"],
  },
  {
    id: "p4",
    name: "Thunder Gaming Chair RGB",
    brand: "Green Soul",
    category: "gaming-chairs",
    description: "Ultimate gaming chair with RGB lighting, neck pillow, lumbar support cushion, and 4D adjustable armrests. Built for marathon gaming sessions.",
    material: "PU Leather",
    frameMaterial: "Steel",
    seatHeight: "47cm - 57cm",
    weightCapacity: "130 kg",
    armrest: "4D Adjustable",
    headrest: "Yes",
    recline: "Yes (90-180 degrees)",
    warranty: "2 Years",
    assemblyRequired: true,
    colors: ["Black-Red", "Black-Blue", "Black-Green"],
    dimensions: "72cm x 70cm x 130cm",
    weight: "18 kg",
    mrp: 32999,
    sellingPrice: 22999,
    gstPercent: 18,
    stockQty: 15,
    sku: "GS-GAME-RGB-004",
    images: [
      "https://images.unsplash.com/photo-1598550476439-6847785fcea6?w=600",
      "https://images.unsplash.com/photo-1580480055273-228ff5388ef8?w=600",
    ],
    isFeatured: true,
    rating: 4.6,
    reviewCount: 312,
    tags: ["gaming", "RGB", "recline", "premium"],
  },
  {
    id: "p5",
    name: "RelaxMax Recliner",
    brand: "Durian",
    category: "recliner-chairs",
    description: "Premium single-seater recliner with manual recline mechanism. Soft leatherette upholstery and padded armrests for ultimate relaxation.",
    material: "Leatherette",
    frameMaterial: "Hardwood",
    seatHeight: "42cm",
    weightCapacity: "120 kg",
    armrest: "Yes",
    headrest: "Yes",
    recline: "Yes (90-160 degrees)",
    warranty: "2 Years",
    assemblyRequired: false,
    colors: ["Brown", "Black", "Cream"],
    dimensions: "85cm x 90cm x 105cm",
    weight: "22 kg",
    mrp: 45999,
    sellingPrice: 35999,
    gstPercent: 18,
    stockQty: 8,
    sku: "DUR-REL-001",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    ],
    isFeatured: true,
    rating: 4.7,
    reviewCount: 178,
    tags: ["recliner", "luxury", "comfort", "living room"],
  },
  {
    id: "p6",
    name: "Nordic Accent Lounge Chair",
    brand: "Pepperfry",
    category: "lounge-chairs",
    description: "Minimalist Scandinavian-inspired lounge chair with solid wood legs and premium fabric cushioning. A statement piece for your living room.",
    material: "Fabric",
    frameMaterial: "Solid Oak Wood",
    seatHeight: "40cm",
    weightCapacity: "100 kg",
    armrest: "Yes",
    headrest: "No",
    recline: "No",
    warranty: "1 Year",
    assemblyRequired: true,
    colors: ["Mustard", "Teal", "Grey", "Pink"],
    dimensions: "75cm x 78cm x 80cm",
    weight: "9 kg",
    mrp: 22999,
    sellingPrice: 15999,
    gstPercent: 12,
    stockQty: 25,
    sku: "PF-NORD-001",
    images: [
      "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600",
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    ],
    isFeatured: false,
    rating: 4.4,
    reviewCount: 67,
    tags: ["nordic", "lounge", "accent", "modern"],
  },
  {
    id: "p7",
    name: "Task Chair Basic",
    brand: "Godrej Interio",
    category: "office-chairs",
    description: "Affordable and sturdy task chair for everyday office use. Simple design with essential ergonomic features.",
    material: "Mesh + Fabric",
    frameMaterial: "Plastic",
    seatHeight: "43cm - 53cm",
    weightCapacity: "90 kg",
    armrest: "Fixed",
    headrest: "No",
    recline: "Yes (90-110 degrees)",
    warranty: "1 Year",
    assemblyRequired: true,
    colors: ["Black", "Grey"],
    dimensions: "60cm x 60cm x 100cm",
    weight: "9 kg",
    mrp: 8999,
    sellingPrice: 5499,
    gstPercent: 18,
    stockQty: 80,
    sku: "GI-TASK-001",
    images: [
      "https://images.unsplash.com/photo-1523297467724-f6758d7124c5?w=600",
    ],
    isFeatured: false,
    rating: 3.9,
    reviewCount: 445,
    tags: ["task", "affordable", "office", "basic"],
  },
  {
    id: "p8",
    name: "Altura Bar Stool",
    brand: "Featherlite",
    category: "bar-stools",
    description: "Modern bar stool with adjustable height and swivel mechanism. Perfect for kitchen counters, home bars, and cafe setups.",
    material: "PU Leather",
    frameMaterial: "Chrome Steel",
    seatHeight: "60cm - 80cm",
    weightCapacity: "100 kg",
    armrest: "No",
    headrest: "No",
    recline: "No",
    warranty: "1 Year",
    assemblyRequired: false,
    colors: ["Black", "White", "Red"],
    dimensions: "40cm x 40cm x 90cm",
    weight: "7 kg",
    mrp: 7999,
    sellingPrice: 4999,
    gstPercent: 18,
    stockQty: 35,
    sku: "FL-BAR-001",
    images: [
      "https://images.unsplash.com/photo-1561677843-39dee7a319ca?w=600",
    ],
    isFeatured: false,
    rating: 4.2,
    reviewCount: 93,
    tags: ["bar stool", "adjustable", "swivel", "kitchen"],
  },
  {
    id: "p9",
    name: "Cloud Comfort Armchair",
    brand: "Durian",
    category: "armchairs",
    description: "Plush armchair with deep seating and cloud-like cushioning. Wrapped in premium velvet fabric for a luxurious feel.",
    material: "Velvet Fabric",
    frameMaterial: "Hardwood",
    seatHeight: "38cm",
    weightCapacity: "110 kg",
    armrest: "Yes",
    headrest: "No",
    recline: "No",
    warranty: "2 Years",
    assemblyRequired: false,
    colors: ["Emerald Green", "Navy Blue", "Blush Pink", "Charcoal"],
    dimensions: "80cm x 85cm x 85cm",
    weight: "14 kg",
    mrp: 28999,
    sellingPrice: 19999,
    gstPercent: 12,
    stockQty: 18,
    sku: "DUR-ARM-001",
    images: [
      "https://images.unsplash.com/photo-1586023492125-27b2c045efd7?w=600",
      "https://images.unsplash.com/photo-1506439773649-6e0eb8cfb237?w=600",
    ],
    isFeatured: true,
    rating: 4.8,
    reviewCount: 142,
    tags: ["armchair", "velvet", "luxury", "plush"],
  },
  {
    id: "p10",
    name: "Kiddo Fun Chair",
    brand: "Nilkamal",
    category: "kids-chairs",
    description: "Colorful and sturdy kids chair made from high-quality plastic. Safe, lightweight, and easy to clean. Perfect for study desks.",
    material: "Polypropylene Plastic",
    frameMaterial: "Plastic",
    seatHeight: "30cm",
    weightCapacity: "50 kg",
    armrest: "No",
    headrest: "No",
    recline: "No",
    warranty: "1 Year",
    assemblyRequired: false,
    colors: ["Red", "Yellow", "Blue", "Green"],
    dimensions: "35cm x 35cm x 65cm",
    weight: "2 kg",
    mrp: 1999,
    sellingPrice: 1299,
    gstPercent: 12,
    stockQty: 100,
    sku: "NIL-KIDS-001",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    ],
    isFeatured: false,
    rating: 4.0,
    reviewCount: 288,
    tags: ["kids", "plastic", "colorful", "lightweight"],
  },
  {
    id: "p11",
    name: "Garden Breeze Outdoor Chair",
    brand: "Cello",
    category: "outdoor-chairs",
    description: "Durable outdoor chair made from UV-resistant polypropylene. Stackable design for easy storage. Ideal for gardens, balconies, and patios.",
    material: "UV-Resistant Plastic",
    frameMaterial: "Polypropylene",
    seatHeight: "43cm",
    weightCapacity: "110 kg",
    armrest: "Yes",
    headrest: "No",
    recline: "No",
    warranty: "1 Year",
    assemblyRequired: false,
    colors: ["White", "Green", "Brown"],
    dimensions: "55cm x 52cm x 85cm",
    weight: "3.5 kg",
    mrp: 3499,
    sellingPrice: 2199,
    gstPercent: 5,
    stockQty: 75,
    sku: "CEL-OUT-001",
    images: [
      "https://images.unsplash.com/photo-1600210492486-724fe5c67fb0?w=600",
    ],
    isFeatured: false,
    rating: 4.1,
    reviewCount: 201,
    tags: ["outdoor", "garden", "stackable", "weather-resistant"],
  },
  {
    id: "p12",
    name: "ProLite Foldable Chair",
    brand: "Nilkamal",
    category: "foldable-chairs",
    description: "Lightweight and portable foldable chair perfect for events, home use, and travel. Quick fold mechanism with carry handle.",
    material: "HDPE Plastic",
    frameMaterial: "Steel",
    seatHeight: "44cm",
    weightCapacity: "120 kg",
    armrest: "No",
    headrest: "No",
    recline: "No",
    warranty: "1 Year",
    assemblyRequired: false,
    colors: ["Black", "White", "Blue"],
    dimensions: "43cm x 47cm x 78cm",
    weight: "3 kg",
    mrp: 2499,
    sellingPrice: 1599,
    gstPercent: 5,
    stockQty: 150,
    sku: "NIL-FOLD-001",
    images: [
      "https://images.unsplash.com/photo-1555041469-a586c61ea9bc?w=600",
    ],
    isFeatured: false,
    rating: 3.8,
    reviewCount: 367,
    tags: ["foldable", "portable", "lightweight", "events"],
  },
];

export const reviews: Review[] = [
  {
    id: "r1",
    productId: "p1",
    customerName: "Rahul Sharma",
    rating: 5,
    reviewText: "Bahut achhi chair hai! Puri din kaam karta hoon aur kamar mein dard nahi hota. Highly recommended!",
    date: "2025-01-15",
    isVerified: true,
    helpful: 45,
  },
  {
    id: "r2",
    productId: "p1",
    customerName: "Priya Gupta",
    rating: 4,
    reviewText: "Good quality chair. Assembly thodi mushkil thi but overall satisfied. Mesh breathable hai.",
    date: "2025-01-10",
    isVerified: true,
    helpful: 28,
  },
  {
    id: "r3",
    productId: "p4",
    customerName: "Vikash Kumar",
    rating: 5,
    reviewText: "Gaming ke liye perfect! RGB lighting bahut cool lagti hai. Comfortable hai 6-8 ghante gaming ke liye.",
    date: "2025-01-20",
    isVerified: true,
    helpful: 67,
  },
  {
    id: "r4",
    productId: "p5",
    customerName: "Sunita Devi",
    rating: 5,
    reviewText: "Raat ko TV dekhne ke liye ekdum sahi. Bahut aaram deta hai. Quality top notch hai.",
    date: "2025-01-05",
    isVerified: true,
    helpful: 89,
  },
];

export const orders: Order[] = [
  {
    id: "ORD-2025-001",
    date: "2025-01-18",
    status: "Delivered",
    items: [
      { product: products[0], quantity: 1, selectedColor: "Black" },
    ],
    total: 15298,
    address: {
      id: "a1",
      label: "Home",
      name: "Rahul Sharma",
      mobile: "9876543210",
      address: "123, Sector 18",
      city: "Noida",
      state: "Uttar Pradesh",
      pincode: "201301",
      isDefault: true,
    },
    paymentMethod: "UPI",
  },
  {
    id: "ORD-2025-002",
    date: "2025-01-22",
    status: "Shipped",
    items: [
      { product: products[3], quantity: 1, selectedColor: "Black-Red" },
    ],
    total: 27118,
    address: {
      id: "a1",
      label: "Home",
      name: "Rahul Sharma",
      mobile: "9876543210",
      address: "123, Sector 18",
      city: "Noida",
      state: "Uttar Pradesh",
      pincode: "201301",
      isDefault: true,
    },
    paymentMethod: "Credit Card",
  },
];

export const coupons: Coupon[] = [
  { code: "CHAIR10", type: "percent", value: 10, minOrderValue: 5000 },
  { code: "SAVE500", type: "flat", value: 500, minOrderValue: 3000 },
  { code: "NEWUSER", type: "percent", value: 15, minOrderValue: 2000 },
];

export const brands = ["Green Soul", "Godrej Interio", "Featherlite", "Durian", "Nilkamal", "Cello", "Pepperfry"];

export const banners = [
  {
    id: "b1",
    title: "Summer Sale",
    subtitle: "Upto 40% off on all office chairs",
    cta: "Shop Now",
    bg: "from-amber-500 to-orange-600",
    image: "office",
  },
  {
    id: "b2",
    title: "New Arrivals",
    subtitle: "Premium gaming chairs now in stock",
    cta: "Explore",
    bg: "from-purple-600 to-indigo-700",
    image: "gaming",
  },
  {
    id: "b3",
    title: "Free Delivery",
    subtitle: "On orders above ₹5000",
    cta: "Browse Chairs",
    bg: "from-emerald-500 to-teal-600",
    image: "delivery",
  },
];
